[unstable]
build-std = ["core"]

[build]
target = "thumbv4t-none-eabi"

[target.thumbv4t-none-eabi]
rustflags = [
  "-Clinker=arm-none-eabi-ld", # uses the ARM linker
  "-Clink-arg=-Tlinker_scripts/mono_boot.ld", # sets the link script
]
runner = ["mgba", "-C", "logToStdout=1", "-C", "logLevel.gba.debug=127"]
